version: '3.7'

services:
  # Postgres
  postgres:
    # container_name: postgres
    build: ./api/postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"

  # Backend api
  smart-brain-api-1:
    container_name: backend
    build: ./api # build using the Dockerfile at ./
    command: npm start
    working_dir: /usr/src/smart-brain-api-1/api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
      AUTHORIZATION_URI: auth://auth:23456
    # links:
    #   - authorization
    ports:
     - "3000:3000"
    #  - "23455:23455"
    volumes:
     - ./api:/usr/src/smart-brain-api-1/api

  # authorization
  authorization:
    container_name: auth
    build: ./authorization # build using the Dockerfile at ./
    command: npm start
    working_dir: /usr/src/smart-brain-api-1/authorization
    environment:
      REDIS_URI: redis://redis:6379
    # links:
    #   - smart-brain-api-1
    ports:
     - "23456:23456"
    volumes:
     - ./authorization:/usr/src/smart-brain-api-1/authorization

  

  