version: '3.7'

services:

  # Backend api
  smart-brain-api-1:
    container_name: backend
    build: ./ # build using the Dockerfile at ./
    command: npm start
    working_dir: /usr/src/smart-brain-api-1
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    # links:
    #   - postgres
    ports:
     - "3000:3000"
    volumes:
     - ./:/usr/src/smart-brain-api-1

  # Postgres
  postgres:
    # container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"